name: 📦 Deliver icons to poc-monorepo-2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "assets/icons/*"

jobs:
  deliver_icons_to_spark_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: lts/Hydrogen
          cache: "npm"
      # TODO: Needed ?
      # - name: Install svgo
      #   run: npm -g install svgo@4.0.0
      - name: Deliver Icons To Spark iOS
        uses: cpina/github-action-push-to-another-repository@v1.7.3
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_IOS }}
        with:
          source-directory: "assets/spark/icons"
          destination-github-username: "poc-username"
          destination-repository-name: "poc-monorepo-2"
          user-email: ${{ secrets.API_GITHUB_COMMIT_EMAIL }}
          commit-message: |
            feat(icons): update icons"

            See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: chore-updated-icons
          create-target-branch-if-needed: true
          target-directory: "spark-token/iconography"
